db.getSiblingDB("trade").createCollection("bybit_executions",   { timeseries: {timeField: "unixtime", metaField: "metadata", bucketMaxSpanSeconds: 360, bucketRoundingSeconds: 360 }})
db.getSiblingDB("trade").createCollection("bybit_orderbook",    { timeseries: {timeField: "unixtime", metaField: "metadata", bucketMaxSpanSeconds: 360, bucketRoundingSeconds: 360 }})
db.getSiblingDB("trade").createCollection("bybit_kline",        { timeseries: {timeField: "unixtime", metaField: "symbol", granularity: "seconds" }})
db.getSiblingDB("trade").createCollection("bybit_ticker",       { timeseries: {timeField: "unixtime", metaField: "symbol", granularity: "seconds" }})
db.getSiblingDB("trade").createCollection("bybit_funding_rate", { timeseries: {timeField: "unixtime", metaField: "symbol", granularity: "hours"   }})
db.getSiblingDB("trade").createCollection("bybit_open_interest",{ timeseries: {timeField: "unixtime", metaField: "symbol", granularity: "minutes" }})
db.getSiblingDB("trade").createCollection("bybit_long_short",   { timeseries: {timeField: "unixtime", metaField: "symbol", granularity: "minutes" }})