INSERT INTO master_symbol (symbol_id, symbol_name, exchange, base, currency, is_active, `explain`) VALUES
(0, 'BTC_JPY', 'bitflyer', 'BTC', 'JPY', 1, NULL),
(1, 'XRP_JPY', 'bitflyer', 'XRP', 'JPY', 1, NULL),
(2, 'ETH_JPY', 'bitflyer', 'ETH', 'JPY', 1, NULL),
(3, 'XLM_JPY', 'bitflyer', 'XLM', 'JPY', 0, NULL),
(4, 'MONA_JPY', 'bitflyer', 'MONA', 'JPY', 0, NULL),
(5, 'FX_BTC_JPY', 'bitflyer', 'BTC_FX', 'JPY', 1, NULL),
(6, 'spot@BTCUSDT', 'bybit', 'BTC', 'USDT', 1, NULL),
(7, 'spot@ETHUSDC', 'bybit', 'ETH', 'USDC', 1, NULL),
(8, 'spot@BTCUSDC', 'bybit', 'BTC', 'USDC', 1, NULL),
(9, 'spot@ETHUSDT', 'bybit', 'ETH', 'USDT', 1, NULL),
(10, 'spot@XRPUSDT', 'bybit', 'XRP', 'USDT', 1, NULL),
(11, 'linear@BTCUSDT', 'bybit', 'BTC', 'USDT', 1, NULL),
(12, 'linear@ETHUSDT', 'bybit', 'ETH', 'USDT', 1, NULL),
(13, 'linear@XRPUSDT', 'bybit', 'XRP', 'USDT', 1, NULL),
(14, 'inverse@BTCUSD', 'bybit', 'BTC', 'USD', 1, NULL),
(15, 'inverse@ETHUSD', 'bybit', 'ETH', 'USD', 1, NULL),
(16, 'inverse@XRPUSD', 'bybit', 'XRP', 'USD', 1, NULL),
(17, 'USDJPY.FOREX', 'eodhd', 'USD', 'JPY', 1, NULL),
(18, 'EURUSD.FOREX', 'eodhd', 'EUR', 'USD', 1, NULL),
(19, 'GBPUSD.FOREX', 'eodhd', 'GBP', 'USD', 1, NULL),
(20, 'USDCHF.FOREX', 'eodhd', 'USD', 'CHF', 1, NULL),
(21, 'AUDUSD.FOREX', 'eodhd', 'AUD', 'USD', 1, NULL),
(22, 'USDCAD.FOREX', 'eodhd', 'USD', 'CAD', 1, NULL),
(23, 'NZDUSD.FOREX', 'eodhd', 'NZD', 'USD', 1, NULL),
(24, 'EURGBP.FOREX', 'eodhd', 'EUR', 'GBP', 1, NULL),
(25, 'EURJPY.FOREX', 'eodhd', 'EUR', 'JPY', 1, NULL),
(26, 'EURCHF.FOREX', 'eodhd', 'EUR', 'CHF', 1, NULL),
(27, 'XAUUSD.FOREX', 'eodhd', 'XAU', 'USD', 1, NULL),
(28, 'GSPC.INDX', 'eodhd', 'GSPC', 'USD', 1, 'S&P 500'),
(29, 'DJI.INDX', 'eodhd', 'DJI', 'USD', 1, 'Dow Jones'),
(30, 'IXIC.INDX', 'eodhd', 'IXIC', 'USD', 1, 'NASDAQ Index'),
(31, 'BUK100P.INDX', 'eodhd', 'BUK100P', 'GBP', 1, 'Cboe UK 100'),
(32, 'VIX.INDX', 'eodhd', 'VIX', 'USD', 1, 'CBOE Volatility Index'),
(33, 'GDAXI.INDX', 'eodhd', 'GDAXI', 'EUR', 1, 'Germany 40 index'),
(34, 'FCHI.INDX', 'eodhd', 'FCHI', 'EUR', 1, 'France 40 index'),
(35, 'STOXX50E.INDX', 'eodhd', 'STOXX50E', 'EUR', 1, 'Europe 50 index'),
(36, 'N100.INDX', 'eodhd', 'N100', 'EUR', 1, 'Euronext 100 Index'),
(37, 'BFX.INDX', 'eodhd', 'BFX', 'EUR', 1, 'Brussels 20 Index'),
(38, 'IMOEX.INDX', 'eodhd', 'IMOEX', 'RUB', 0, 'Russia 50 Index'),
(39, 'N225.INDX', 'eodhd', 'N225', 'JPY', 1, 'Nikkei 225'),
(40, 'HSI.INDX', 'eodhd', 'HSI', 'HKD', 1, 'Hong Kong 40 Index'),
(41, 'SSEC.INDX', 'eodhd', 'SSEC', '', 0, NULL),
(42, 'AORD.INDX', 'eodhd', 'AORD', 'AUD', 1, 'Australlia 500 index'),
(43, 'BSESN.INDX', 'eodhd', 'BSESN', 'INR', 1, 'india 30 index'),
(44, 'JKSE.INDX', 'eodhd', 'JKSE', 'IDR', 1, 'Jakarta all Index'),
(45, 'NZ50.INDX', 'eodhd', 'NZ50', 'NZD', 1, 'New Zealand 50 Index'),
(46, 'KS11.INDX', 'eodhd', 'KS11', 'KRW', 1, 'Koria Index'),
(47, 'TWII.INDX', 'eodhd', 'TWII', 'TWD', 1, 'Taiwan Index'),
(48, 'GSPTSE.INDX', 'eodhd', 'GSPTSE', 'CAD', 1, 'Canada 250 Index'),
(49, 'BVSP.INDX', 'eodhd', 'BVSP', 'BRL', 1, 'Brazil index'),
(50, 'MXX.INDX', 'eodhd', 'GSPTSE', 'MXN', 1, 'Mexico Index'),
(51, 'SPIPSA.INDX', 'eodhd', 'SPIPSA', 'CLP', 0, 'Chile Index'),
(52, 'MERV.INDX', 'eodhd', 'MERV', 'ARS', 0, 'Argentina  Index'),
(53, 'TA125.INDX', 'eodhd', 'TA125', 'ILS', 0, 'Israel 125 Index'),
(54, 'USA500IDXUSD', 'dukascopy', 'GSPC', 'USD', 1, 'S&P 500'),
(55, 'VOLIDXUSD', 'dukascopy', 'VIX', 'USD', 1, 'CBOE Volatility Index'),
(56, 'CHIIDXUSD', 'dukascopy', 'XIN9', 'CNY', 1, 'China A50 Index'),
(57, 'HKGIDXHKD', 'dukascopy', 'HSI', 'HKD', 1, 'Hong Kong 40 Index'),
(58, 'JPNIDXJPY', 'dukascopy', 'N225', 'JPY', 1, 'Nikkei 225'),
(59, 'AUSIDXAUD', 'dukascopy', 'AXJO', 'AUD', 1, 'Australlia 200 index'),
(60, 'INDIDXUSD', 'dukascopy', 'NSEI', 'INR', 1, 'India 50 index'),
(61, 'SGDIDXSGD', 'dukascopy', 'SSGF3', 'SGD', 1, 'Singapore Blue Chip'),
(62, 'FRAIDXEUR', 'dukascopy', 'FCHI', 'EUR', 1, 'France 40 index'),
(63, 'DEUIDXEUR', 'dukascopy', 'GDAXI', 'EUR', 1, 'Germany 40 index'),
(64, 'EUSIDXEUR', 'dukascopy', 'STOXX50E', 'EUR', 1, 'Europe 50 index'),
(65, 'GBRIDXGBP', 'dukascopy', 'BUK100P', 'GBP', 1, 'UK 100 index'),
(66, 'ESPIDXEUR', 'dukascopy', 'IBEX', 'EUR', 1, 'Spain 35 index'),
(67, 'CHEIDXCHF', 'dukascopy', 'SPI20', 'CHF', 1, 'Switzerland 20 index'),
(68, 'NLDIDXEUR', 'dukascopy', 'NL25', 'EUR', 1, 'Netherlands 25 index'),
(69, 'PLNIDXPLN', 'dukascopy', 'WIG20', 'PLN', 1, 'Poland 20 index'),
(70, 'SOAIDXZAR', 'dukascopy', 'SA40', 'ZAR', 1, 'South Africa 40 index'),
(71, 'USDJPY', 'dukascopy', 'USD', 'JPY', 1, NULL),
(72, 'EURUSD', 'dukascopy', 'EUR', 'USD', 1, NULL),
(73, 'GBPUSD', 'dukascopy', 'GBP', 'USD', 1, NULL),
(74, 'USDCHF', 'dukascopy', 'USD', 'CHF', 1, NULL),
(75, 'AUDUSD', 'dukascopy', 'AUD', 'USD', 1, NULL),
(76, 'USDCAD', 'dukascopy', 'USD', 'CAD', 1, NULL),
(77, 'NZDUSD', 'dukascopy', 'NZD', 'USD', 1, NULL),
(78, 'EURGBP', 'dukascopy', 'EUR', 'GBP', 1, NULL),
(79, 'EURJPY', 'dukascopy', 'EUR', 'JPY', 1, NULL),
(80, 'EURCHF', 'dukascopy', 'EUR', 'CHF', 1, NULL),
(81, 'XAUUSD', 'dukascopy', 'XAU', 'USD', 1, NULL),
(82, 'XAGUSD', 'dukascopy', 'XAG', 'USD', 1, NULL),
(83, 'USA500.IDX/USD', 'dukascopyapi', 'GSPC', 'USD', 1, 'S&P 500'),
(84, 'VOL.IDX/USD', 'dukascopyapi', 'VIX', 'USD', 1, 'CBOE Volatility Index'),
(85, 'CHI.IDX/USD', 'dukascopyapi', 'XIN9', 'CNY', 1, 'China A50 Index'),
(86, 'HKG.IDX/HKD', 'dukascopyapi', 'HSI', 'HKD', 1, 'Hong Kong 40 Index'),
(87, 'JPN.IDX/JPY', 'dukascopyapi', 'N225', 'JPY', 1, 'Nikkei 225'),
(88, 'AUS.IDX/AUD', 'dukascopyapi', 'AXJO', 'AUD', 1, 'Australlia 200 index'),
(89, 'IND.IDX/USD', 'dukascopyapi', 'NSEI', 'INR', 1, 'India 50 index'),
(90, 'SGD.IDX/SGD', 'dukascopyapi', 'SSGF3', 'SGD', 1, 'Singapore Blue Chip'),
(91, 'FRA.IDX/EUR', 'dukascopyapi', 'FCHI', 'EUR', 1, 'France 40 index'),
(92, 'DEU.IDX/EUR', 'dukascopyapi', 'GDAXI', 'EUR', 1, 'Germany 40 index'),
(93, 'EUS.IDX/EUR', 'dukascopyapi', 'STOXX50E', 'EUR', 1, 'Europe 50 index'),
(94, 'GBR.IDX/GBP', 'dukascopyapi', 'BUK100P', 'GBP', 1, 'UK 100 index'),
(95, 'ESP.IDX/EUR', 'dukascopyapi', 'IBEX', 'EUR', 1, 'Spain 35 index'),
(96, 'CHE.IDX/CHF', 'dukascopyapi', 'SPI20', 'CHF', 1, 'Switzerland 20 index'),
(97, 'NLD.IDX/EUR', 'dukascopyapi', 'NL25', 'EUR', 1, 'Netherlands 25 index'),
(98, 'PLN.IDX/PLN', 'dukascopyapi', 'WIG20', 'PLN', 1, 'Poland 20 index'),
(99, 'SOA.IDX/ZAR', 'dukascopyapi', 'SA40', 'ZAR', 1, 'South Africa 40 index'),
(100, 'USD/JPY', 'dukascopyapi', 'USD', 'JPY', 1, NULL),
(101, 'EUR/USD', 'dukascopyapi', 'EUR', 'USD', 1, NULL),
(102, 'GBP/USD', 'dukascopyapi', 'GBP', 'USD', 1, NULL),
(103, 'USD/CHF', 'dukascopyapi', 'USD', 'CHF', 1, NULL),
(104, 'AUD/USD', 'dukascopyapi', 'AUD', 'USD', 1, NULL),
(105, 'USD/CAD', 'dukascopyapi', 'USD', 'CAD', 1, NULL),
(106, 'NZD/USD', 'dukascopyapi', 'NZD', 'USD', 1, NULL),
(107, 'EUR/GBP', 'dukascopyapi', 'EUR', 'GBP', 1, NULL),
(108, 'EUR/JPY', 'dukascopyapi', 'EUR', 'JPY', 1, NULL),
(109, 'EUR/CHF', 'dukascopyapi', 'EUR', 'CHF', 1, NULL),
(110, 'XAU/USD', 'dukascopyapi', 'XAU', 'USD', 1, NULL),
(111, 'XAG/USD', 'dukascopyapi', 'XAG', 'USD', 1, NULL),
(112, 'AXJO.INDX', 'eodhd', 'AXJO', 'AUD', 1, 'S&P/ASX 200'),
(113, 'NSEI.INDX', 'eodhd', 'NSEI', 'INR', 1, 'Nifty 50'),
(114, 'IBEX.INDX', 'eodhd', 'IBEX', 'EUR', 1, 'IBEX 35 Index'),
(115, 'SPI20.INDX', 'eodhd', 'SPI20', 'CHF', 0, 'SPI 20 PR (Not available)'),
(116, 'AEX.INDX', 'eodhd', 'NL25', 'EUR', 1, 'AEX Amsterdam Index'),
(117, 'WIG20.INDX', 'eodhd', 'WIG20', 'PLN', 0, 'Poland 20 index (Not available)'),
(118, 'XAGUSD.FOREX', 'eodhd', 'XAG', 'USD', 1, NULL);

INSERT INTO master_symbol (symbol_id, symbol_name, exchange, base, currency, is_active, `explain`) VALUES
(119, 'SPOT@BTCUSDT', 'binance', 'BTC', 'USDT', 1, NULL),
(120, 'SPOT@ETHUSDC', 'binance', 'ETH', 'USDC', 1, NULL),
(121, 'SPOT@BTCUSDC', 'binance', 'BTC', 'USDC', 1, NULL),
(122, 'SPOT@ETHUSDT', 'binance', 'ETH', 'USDT', 1, NULL),
(123, 'SPOT@XRPUSDT', 'binance', 'XRP', 'USDT', 1, NULL),
(124, 'USDS@BTCUSDT', 'binance', 'BTC', 'USDT', 1, NULL),
(125, 'USDS@ETHUSDT', 'binance', 'ETH', 'USDT', 1, NULL),
(126, 'USDS@XRPUSDT', 'binance', 'XRP', 'USDT', 1, NULL),
(127, 'COIN@BTCUSD_PERP', 'binance', 'BTC', 'USD', 1, NULL),
(128, 'COIN@ETHUSD_PERP', 'binance', 'ETH', 'USD', 1, NULL),
(129, 'COIN@XRPUSD_PERP', 'binance', 'XRP', 'USD', 1, NULL);
